### ISSUE TITLE
javah failed with ClassCastException

### ISSUE THREAD

**Issue by rzeigler** [sbt/sbt-jni#38] opened 2021-01-04 17:49 UTC
See the following stack trace that happens under sbt 1.4.5

```
[error] java.lang.ClassCastException: class sbt.internal.inc.MappedVirtualFile cannot be cast to class java.io.File (sbt.internal.inc.MappedVirtualFile is in unnamed module of loader sbt.internal.MetaBuildLoader @5bf0d49; java.io.File is in module java.base of loader 'bootstrap')
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:292)
[error]         at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:330)
[error]         at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:1104)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:292)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:289)
[error]         at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error]         at ch.jodersky.sbt.jni.plugins.JniJavah$.$anonfun$mainSettings$1(JniJavah.scala:38)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
[error] (corev2bench / javah / javahClasses) java.lang.ClassCastException: class sbt.internal.inc.MappedVirtualFile cannot be cast to class java.io.File (sbt.internal.inc.MappedVirtualFile is in unnamed module of loader sbt.internal.MetaBuildLoader @5bf0d49; java.io.File is in module java.base of loader 'bootstrap')
```

**Comment by jodersky** [comment] 2021-01-07 18:08
Can't help without more info

**Comment by rzeigler** [comment] 2021-01-08 16:13
What additional information would you like?

**Comment by SlavikBaranov** [comment] 2021-03-16 20:16
This problem happens on sbt 1.4.x because `getAllProductStamps` now returns `Map<VirtualFileRef, Stamp>` instead of `Map<File, Stamp>`: 
 https://github.com/sbt/zinc/commit/db028c338af528876e24fc8d6214e24f7d19d707#diff-e9a05cdc20dd4249f04d5f9c05b11893d58b619833d4a8589e65d9ff4ed64a1f
 
Easiest way to reproduce the problem is to bump sbt version in the project to 1.4.7, it won't compile any more. It would be great if you could look into it.

**Comment by kammoh** [comment] 2021-03-31 22:21
I'm having the same issue with sbt 1.4.9:
```
sbt:myproject> javah
[error] (myproject / javah / javahClasses) java.lang.ClassCastException: class sbt.internal.inc.MappedVirtualFile cannot be cast to class java.io.File (sbt.internal.inc.MappedVirtualFile is in unnamed module of loader sbt.internal.MetaBuildLoader @55040f2f; java.io.File is in module java.base of loader 'bootstrap')
```

**Comment by kammoh** [comment] 2021-04-01 01:56
#39 seems to be working for me. I know nothing about about `sbt` so chances are I didn't get it right, but please feel free to try it out!

**Comment by sideeffffect** [comment] 2021-05-04 15:16
Can you @jodersky please release a new version with the recently merged fix?

**Comment by pomadchin** [comment] 2021-07-26 23:41
1.5.0 release happened! 🎉 https://github.com/sbt/sbt-jni/releases/tag/v1.5.0

**Closed by pomadchin** 2021-07-26 23:41 UTC
Labels: bug
